<a href="https://colab.research.google.com/github/akhilesh2009/Exploring-the-Titanic-Dataset/blob/main/Exploring_the_Titanic_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Study Titanic passengers to find what factors improved survival odds.**

In [152]:
import pandas as pd
import matplotlib.pyplot as plt

In [153]:
train = pd.read_csv("train.csv")

In [154]:
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [155]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [156]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [157]:
train.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

# **Total Survived**

Total number of Passengers survived

In [188]:
total_passengers_survive = train["Survived"].value_counts()[1]
print(total_passengers_survive)

342

# **Survival by Gender**

In [159]:
survival_by_gender = train.groupby("Sex")["Survived"].sum()
survival_by_gender

Sex
female    233
male      109
Name: Survived, dtype: int64

Number of Females Survived

In [160]:
females_survive = survival_by_gender["female"]
print(f"Number of females survived: {females_survive}")

Number of females survived: 233

Number of males Survived

In [161]:
males_survives = survival_by_gender["male"]
print(f"Number of males survived: {males_survives}")

Number of males survived: 109

**Females have higher rate of survival then males**

Percent of Males Survived

In [163]:
percent_males_survived = (males_survives / total_passengers_survive) * 100
print(percent_males_survived)

31.871345029239766

Percent of Females Survived

In [164]:
percent_females_survived = (females_survive / total_passengers_survive) * 100
print(percent_females_survived)

68.12865497076024

# **Survival rate by Pclass**

In [165]:
survival_by_class = train.groupby("Pclass")["Survived"].sum()
survival_by_class

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

Number of survived passenger from Pclass 1

In [166]:
survive_class_1 = survival_by_class[1]
survive_class_1

np.int64(136)

Number of survived passenger from Pclass 2

In [167]:
survive_class_2 = survival_by_class[2]
survive_class_2

np.int64(87)

Number of survived passenger from Pclass 3

In [168]:
survive_class_3 = survival_by_class[3]
survive_class_3

np.int64(119)

Percent of survived passenger from Pclass 1

In [169]:
percent_class1_survive = (survive_class_1 / total_passengers_survive) * 100
percent_class1_survive

np.float64(39.76608187134503)

Percent of survived passenger from Pclass 2

In [170]:
percent_class2_survive = (survive_class_2 / total_passengers_survive) * 100
percent_class2_survive

np.float64(25.438596491228072)

Percent of survived passenger from Pclass 3

In [171]:
percent_class3_survive = (survive_class_3 / total_passengers_survive) * 100
percent_class3_survive

np.float64(34.7953216374269)

# **Survival rate by Age group**

Age column

In [172]:
train["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

People with NaN age

In [173]:
train[train["Age"].isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

Total number of people with NaN age survived

In [174]:
nan_age_survived = len(train[(train["Age"].isna()) & (train["Survived"] == 1)])
nan_age_survived

52

minimum age

In [175]:
train["Age"].min()

0.42

maximum age

In [176]:
train["Age"].max()

80.0

Survial rate of Childs

In [177]:
age_survived = train.groupby("Age")["Survived"].sum()
age_survived

Age
0.42     1
0.67     1
0.75     2
0.83     2
0.92     1
        ..
70.00    0
70.50    0
71.00    0
74.00    0
80.00    1
Name: Survived, Length: 88, dtype: int64

Survial of people b/w age 0 to 12

In [178]:
child_survived = age_survived[0:12].sum()
print(child_survived)

40

/tmp/ipykernel_1819/367405997.py:1: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  child_survived = age_survived[0:12].sum()

Survival of people b/w age 13 to 19

In [179]:
teen_survived = age_survived[13:19].sum()
teen_survived

/tmp/ipykernel_1819/1426549201.py:1: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  teen_survived = age_survived[13:19].sum()

np.int64(39)

survival of people b/w age 20 to 39

In [180]:
adult_survived = age_survived[20:39].sum()
adult_survived

/tmp/ipykernel_1819/4227214267.py:1: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  adult_survived = age_survived[20:39].sum()

np.int64(150)

survival of people b/w age 40 to 59

In [182]:
middle_age_survived = age_survived[50:59].sum()
middle_age_survived

/tmp/ipykernel_1819/1253545223.py:1: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  middle_age_survived = age_survived[50:59].sum()

np.int64(20)

survival of people age 60+

In [186]:
senior_age_survived = age_survived[60:].sum()
senior_age_survived

/tmp/ipykernel_1819/2033758482.py:1: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  senior_age_survived = age_survived[60:].sum()

np.int64(7)

percent of child survived

In [189]:
percent_child_survived = (child_survived / total_passengers_survive) * 100
percent_child_survived

np.float64(11.695906432748536)

percent teen survived

In [190]:
percent_teen_survived = (teen_survived / total_passengers_survive) * 100
percent_teen_survived

np.float64(11.403508771929824)

percent adult survived

In [191]:
percent_adult_survived = (adult_survived / total_passengers_survive) * 100
percent_adult_survived

np.float64(43.859649122807014)

percent middled age survived

In [195]:
percent_middle_age_survived = (middle_age_survived / total_passengers_survive) * 100
percent_middle_age_survived

np.float64(5.847953216374268)

percent senior age survived

In [196]:
percent_senior_survived = (senior_age_survived / total_passengers_survive) * 100
percent_senior_survived

np.float64(2.046783625730994)